export const citations = [
    "La vie est belle, même dans les moments difficiles.",
    "Le bonheur est une décision que l'on prend chaque jour.",
    "La sagesse commence par l'émerveillement.",
    "Le courage n'est pas l'absence de peur, mais la maîtrise de celle-ci.",
    "Les rêves sont faits pour être réalisés.",
    "La patience est la clé de toutes les portes.",
    "La beauté est dans l'œil de celui qui regarde.",
    "Le temps est le meilleur des professeurs.",
    "Chaque jour est une nouvelle chance de réussir.",
    "Le silence est d'or, la parole est d'argent.",
    "Il n'y a pas de hasard, seulement des rendez-vous.",
    "L'espoir fait vivre, la patience fait réussir.",
    "Le bonheur ne se trouve pas, il se construit.",
    "Rien n'est impossible à celui qui croit.",
    "Le temps guérit toutes les blessures.",
    "L'amour est la seule chose qui double à chaque fois qu'on le partage.",
    "Le respect se gagne, il ne se demande pas.",
    "On ne voit bien qu'avec le cœur, l'essentiel est invisible pour les yeux.",
    "La simplicité est la sophistication suprême.",
    "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.",
    "Il vaut mieux être seul que mal accompagné.",
    "Qui ne tente rien n'a rien.",
    "L'avenir appartient à ceux qui se lèvent tôt.",
    "Le bonheur est fait de petites choses.",
    "L'expérience est le nom que chacun donne à ses erreurs.",
    "La réussite est la somme de petits efforts, répétés jour après jour.",
    "Il n'y a pas de réussite facile ni d'échecs définitifs.",
    "La seule chose permanente dans la vie, c'est le changement.",
    "La gratitude transforme ce que nous avons en suffisance.",
    "Le plus grand risque est de ne jamais prendre de risque.",
    "Le secret du bonheur est de s'intéresser aux petites choses.",
    "La vie commence à la fin de votre zone de confort.",
    "L'échec est le fondement de la réussite.",
    "La beauté commence au moment où vous décidez d'être vous-même.",
    "La meilleure façon de prédire l'avenir est de le créer.",
    "Le sourire est la meilleure arme contre les soucis.",
    "Le temps perdu ne se rattrape jamais.",
    "La réussite est un voyage, pas une destination.",
    "Il n'y a pas de raccourci pour atteindre les endroits où cela vaut la peine d'aller.",
    "Le bonheur est la seule chose qui se multiplie quand on le partage.",
    "La vie est un défi à relever, un bonheur à mériter, une aventure à tenter.",
    "Le succès n'est pas la clé du bonheur, le bonheur est la clé du succès.",
    "Celui qui sait écouter apprend chaque jour quelque chose.",
    "La persévérance est la noblesse de l'obstination.",
    "La plus grande victoire est celle que l'on remporte sur soi-même.",
    "Il n'y a pas de vent favorable pour celui qui ne sait où il va.",
    "Les grandes choses ne se font jamais sans passion.",
    "Celui qui plante des arbres aime les autres.",
    "La vie est un miroir : si tu lui souris, elle te renvoie ton sourire.",
    "Il n'y a pas de plus grand plaisir que de faire plaisir aux autres."
]

export const Timeout: number = 1000